import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#312e38' },
  header: {
    padding: 24,
    paddingTop: 48,
    backgroundColor: '#28262e',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  headerTitle: {
    color: '#f5ede8',
    fontFamily: 'RobotoSlab_500Medium',
    fontSize: 20,
    marginLeft: 16,
  },
  userAvatar: {
    width: 56,
    height: 56,
    borderRadius: 28,
    marginLeft: 'auto',
  },
  providersListContainer: { height: 112 },
  providersList: { paddingHorizontal: 24, paddingVertical: 32 },
  providerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 12,
    marginRight: 16,
    borderRadius: 10,
  },
  providerContainerSelected: { backgroundColor: '#ff9000' },
  providerContainerDefault: { backgroundColor: '#3e3b47' },
  providerAvatar: { width: 32, height: 32, borderRadius: 16 },
  providerName: {
    marginLeft: 8,
    fontFamily: 'RobotoSlab_500Medium',
    fontSize: 16,
  },
  providerNameSelected: { color: '#232129' },
  providerNameDefault: { color: '#f4ede8' },
  calendar: {},
  title: {
    fontFamily: 'RobotoSlab_500Medium',
    color: '#f4ede8',
    fontSize: 24,
    marginHorizontal: 24,
    marginBottom: 24,
  },
  openDatePickerButton: {
    height: 46,
    backgroundColor: '#ff9000',
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: 24,
  },
  openDatePickerButtonText: {
    fontFamily: 'RobotoSlab_500Medium',
    fontSize: 16,
    color: '#232129',
  },
  schedule: { paddingTop: 24, paddingBottom: 16 },
  section: { marginBottom: 24 },
  sectionTitle: {
    fontSize: 18,
    color: '#999591',
    fontFamily: 'RobotoSlab_400Regular',
    marginHorizontal: 24,
    marginBottom: 12,
  },
  sectionContent: { paddingHorizontal: 24 },
  hour: {
    padding: 12,
    borderRadius: 10,
    marginRight: 8,
  },
  hourSelected: { backgroundColor: '#ff9000' },
  hourDefault: { backgroundColor: '#3e3b47' },
  hourUnavailable: { opacity: 0.3 },
  hourText: {
    fontFamily: 'RobotoSlab_400Regular',
    fontSize: 16,
  },
  hourTextSelected: { color: '#232129' },
  hourTextDefault: { color: '#f4ede8' },
  createAppointmentButton: {
    height: 50,
    backgroundColor: '#ff9000',
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: 24,
    marginBottom: 24,
  },
  createAppointmentButtonText: {
    fontFamily: 'RobotoSlab_500Medium',
    fontSize: 18,
    color: '#232129',
  },
});
